### ISSUE TITLE
iOS 12: "TypeError: undefined is not an object (evaluating 'window.PerformanceObserver.supportedEntryTypes.includes')"

### ISSUE THREAD

**Issue by chrskrchr** [signalfx/splunk-browser-otel-js#62]
We upgraded our app from `0.0.13` to `0.0.19` of the client SDK and started seeing this error in our Sentry reports on page load:

<img width="671" alt="Screen Shot 2021-02-05 at 1 40 31 PM" src="https://user-images.githubusercontent.com/805780/107081067-bcd9d280-67b7-11eb-94fc-10980a2fcffb.png">

We then see the following error logged on every route change:
```
TypeError: undefined is not an object (evaluating 'window.SplunkRum.provider.getTracer')
  at value(/app/enrollment/static/splunk-rum-0.0.19.js:1:73806)
  at ? (/app/enrollment/static/splunk-rum-0.0.19.js:1:74376)
  at value(../../../../next-server/lib/router/router.ts:932:7)
  at call(../../../../next-server/lib/router/router.ts:869:7)
  at tryCatch(./node_modules/regenerator-runtime/runtime.js:63:40)
  at key(./node_modules/regenerator-runtime/runtime.js:293:22)
  at asyncGeneratorStep(./node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:20)
  at _next(./node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
  at promiseReactionJob([native code])
```

The error is showing up on the following browsers:

<img width="763" alt="Screen Shot 2021-02-05 at 1 31 29 PM" src="https://user-images.githubusercontent.com/805780/107080165-7df74d00-67b6-11eb-8014-b6df3cee50bd.png">

**Comment by jtmalinowski** [comment]
@chrskrchr That's a great bug submission, thank you.

**Comment by jtmalinowski** [comment]
@chrskrchr We'll let you know when it's released.

**Comment by jtmalinowski** [comment]
@chrskrchr I've just released a new version <https://github.com/signalfx/splunk-otel-js-browser/releases/tag/untagged-6ea4f93875ea30dc44ab>. Browser support should be extended even to Safari 10, of course it's best effort, so not all the functionality will work.

**Comment by chrskrchr** [comment]
Thanks!  We'll pull in the `0.0.20` release ASAP and let you know if we run into any issues.
